const GameGenres = {
    "Simulação": "Simulation",
    "Combate": "Combat",
    "Ficção Científica": "Sci-fi",
    "Ação": "Action",
    "TPP": "TPP",
    "Role-playing": "Role-playing",
    "Aventura": "Adventure",
    "Fantasia": "Fantasy",
    "Tiro": "Shooter",
    "FPP": "FPP",
    "Moderno": "Modern",
    "Estratégia": "Strategy",
    "Por Turnos": "Turn-based",
    "Narrativa": "Narrative",
    "Naval": "Naval",
    "Terror": "Horror",
    "Roguelike": "Roguelike",
    "Quebra-cabeça": "Puzzle",
    "Plataforma": "Platformer",
    "Romance Visual": "Visual Novel",
    "JRPG": "JRPG",
    "Point-and-click": "Point-and-click",
    "Detetive Mistério": "Detective-mystery",
    "Arcade": "Arcade",
    "Comédia": "Comedy",
    "Construção": "Building",
    "Tático": "Tactical",
    "Metroidvânia": "Metroidvania",
    "Econômico": "Economic",
    "Sobrevivência": "Survival",
    "Tempo Real": "Real-time",
    "Mistério": "Mystery",
    "Histórico": "Historical"
};

export default GameGenres;
